### ISSUE TITLE
Boostrap3's carousel

### ISSUE THREAD

**Issue by ThibautAlgrin** [jonom/jquery-focuspoint#52]
Hello,

I have some concerns with the carousel of Boostrap. Indeed, I do not see the other images that the first one. When I investigate there above, I can notice that the image possesses "left: 300 %"

Have you ideas?

**Comment by jonom** [comment]
Hi @ThibautAlgrin I haven't used Bootstrap's carousels but there is a note in the ReadMe about this issue. You probably need to re-fire the focus event for each carousel slide once it becomes visible. FocusPoint can't correctly position an image inside an invisible container because it doesn't have any dimensions.
